### ISSUE TITLE
WorldGuard loading before FAWE 1.13.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/FastAsyncWorldEdit-1.13#47]
FAWE 1.13 compiled as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/24fbc86cdd79b8ce13359342bc422ce1fb25a0d2
WorldGuard dev 1804

@IronApollo WorldGuard tries to load before FAWE, causing initialization to fail for a bunch of plugins. I tentatively fixed this by adjusting the plugin.yml so WorldGuard is not a softdepend and loads before it, at start-up, as well as before another plugin which happened to initialize earlier.
```
[19:53:24] [Server thread/ERROR]: Could not load 'plugins/worldguard-legacy-7.0.0-SNAPSHOT-dist.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/Injector
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:276) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.NoClassDefFoundError: com/sk89q/minecraft/util/commands/Injector
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-525]
	... 6 more
Caused by: java.lang.ClassNotFoundException: com.sk89q.minecraft.util.commands.Injector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:138) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:84) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_202]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:62) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-525]
	... 6 more
[19:53:24] [Server thread/ERROR]: Could not load 'plugins/WorldGuardExtraFlags.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldGuard
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[19:53:24] [Server thread/INFO]: [FastAsyncWorldEdit] Using com.boydti.fawe.bukkit.adapter.v1_13_1.Spigot_v1_13_R2 as the Bukkit adapter
[19:53:25] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[19:53:25] [Server thread/INFO]: [WorldEdit] Logging WorldEdit commands to /home/minecraft/multicraft/servers/server4/plugins/FastAsyncWorldEdit/worldedit.log
[19:53:25] [Server thread/INFO]: finished enable
[19:53:25] [Server thread/ERROR]: Could not load 'plugins/AreaShop.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: WorldGuard
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:218) ~[patched_1.13.2.jar:git-Paper-525]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-525]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786) ~[patched_1.13.2.jar:git-Paper-525]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
[19:53:25] [Server thread/INFO]: [P2] Force loading WorldEdit
[19:53:25] [Server thread/INFO]: [P2] Testing platform capabilities
```

"Fixed" plugin.yml
```
load: STARTUP
loadbefore: [BannerBoard, WorldGuard, PlotSquared, AsyncWorldEdit, AsyncWorldEditInjector]
database: false
softdepend: [MCore, Factions, GriefPrevention, Residence, Towny, PlotMe, PreciousStones]
```

**Comment by AeSix** [comment]
As of FAWE-NVS 165, loading order seems to be:
FAWE
PlotSquared
WorldGuard

You can check my debugpaste here:
https://incendo.org/paste/view/e23eed25bf3d4adc8b63e874a3f41143

**Comment by mibby** [comment]
Re-tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/85bfd16d7c16613e79f49d3acaa17007c09baa3e (03/25 compile) with WorldGuard dev 1828. Load order seems to be working fine without modifying the plugin.yml, so assuming it has been fixed.

**Comment by mibby** [comment]
Re-tested as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/8afd96f03b3ea797208a681672d620eb62e1b9b7 on my production environment, this still happens with WorldGuard dev 1830.

I believe it may have something to do with the plugin WorldGuardExtraFlags trying to load WorldGuard before FAWE? Setting ``load: STARTUP`` and ``loadbefore: [BannerBoard, WorldGuard, PlotSquared, AsyncWorldEdit, AsyncWorldEditInjector]`` fixes the issue.

Upstream WorldEdit does not have this issue.

**Comment by mibby** [comment]
@boy0001 Testing as of commit https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/commit/a636a30e9f618cec37416f0d81ac3ca927a73660, unfortunately that didn't fix it. 

https://paste.ubuntu.com/p/mq5GSMbb6w/

Apologies but I actually forgot to mention what else I did to resolve the issue.

What _does_ actually seem to fix the issue is removing WorldGuard from the softdepend section. Then FAWE and WorldGuard are able to load perfectly fine. I assume FAWE is trying to force WorldGuard to load before it since it is a dependency.

**Comment by mibby** [comment]
Confirmed fixed now, thanks.

**Comment by mrcoffee1026** [comment]
I'm still getting this same issue with
FAWE version 1.0 (as linked from https://empcraft.com/fawe/download/)
and version 1.0 (as linked form https://incendo.org/download)
as well as trying with jenkins builds #147 and #141.  

Worldguards versions attempted latest "stable" 7.0-beta-3
latest dev: #1835

Whatever commit you made seems to be needed again?  Or in some other way?
